### ISSUE TITLE
Bug Report | `Object of type UserSubreddit is not JSON serializable` error when performing a Redditor scrape

### ISSUE THREAD

**Issue by LiqwidSw** [JosephLai241/URS#43]
## Describe The Bug

Getting a `Object of type UserSubreddit is not JSON serializable` error when doing a redditor scrape

## Expected Behavior

Expecting a scrape of a redditor's information and interactions

## Actual Behavior

URS reports an error and only exports a redditor's information 

## Steps To Reproduce

* Ran the commands:

```
python -i F:\urs\urs.py -u ColChrisHadfield 1
python -i F:\urs\urs.py -u wil 1
```

## Traceback, `urs.log`, or Screenshots

```
Traceback (most recent call last):
  File "F:\urs\utils\Logger.py", line 649, in wrapper
    function(*args)
  File "F:\urs\utils\Logger.py", line 312, in wrapper
    settings_dict = function(*args)
  File "F:\urs\praw_scrapers\static_scrapers\Redditor.py", line 564, in run
    Write.write(reddit, u_master)
  File "F:\urs\praw_scrapers\static_scrapers\Redditor.py", line 513, in write
    Export.export(data, f_name, "json", "redditors")
  File "F:\urs\utils\Export.py", line 472, in export
    Export.write_json(data, filename) \
  File "F:\urs\utils\Export.py", line 436, in write_json
    json.dump(data, results, indent = 4)
  File "c:\users\score1\appdata\local\programs\python\python39\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "c:\users\score1\appdata\local\programs\python\python39\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "c:\users\score1\appdata\local\programs\python\python39\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\score1\appdata\local\programs\python\python39\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\score1\appdata\local\programs\python\python39\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\score1\appdata\local\programs\python\python39\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "c:\users\score1\appdata\local\programs\python\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserSubreddit is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\urs\urs.py", line 62, in <module>
    Main.main()
  File "F:\urs\utils\Logger.py", line 76, in wrapper
    function(*args)
  File "F:\urs\urs.py", line 59, in main
    Run(reddit).run_urs()
  File "F:\urs\utils\Tools.py", line 142, in run_urs
    RunRedditor.run(self._args, self._parser, self._reddit)
  File "F:\urs\utils\Logger.py", line 658, in wrapper
    quit()
  File "c:\users\score1\appdata\local\programs\python\python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
```

`urs.log`

```
[2021-07-10 20:25:02,080] [INFO]: INITIALIZING URS.
[2021-07-10 20:25:02,080] [INFO]: 
[2021-07-10 20:25:02,781] [INFO]: RATE LIMIT DISPLAYED.
[2021-07-10 20:25:02,781] [INFO]: Remaining requests: 599.0
[2021-07-10 20:25:02,781] [INFO]: Used requests: 1
[2021-07-10 20:25:02,781] [INFO]: 
[2021-07-10 20:25:02,782] [INFO]: Successfully logged in as u/Score1.
[2021-07-10 20:25:02,782] [INFO]: 
[2021-07-10 20:25:02,782] [INFO]: RUNNING REDDITOR SCRAPER.
[2021-07-10 20:25:02,782] [INFO]: 
[2021-07-10 20:25:02,784] [INFO]: Validating Redditor(s)...
[2021-07-10 20:25:02,784] [INFO]: 
[2021-07-10 20:25:09,936] [CRITICAL]: AN ERROR HAS OCCURRED WHILE EXPORTING SCRAPED DATA.
[2021-07-10 20:25:09,936] [CRITICAL]: Object of type UserSubreddit is not JSON serializable
[2021-07-10 20:25:09,936] [CRITICAL]: ABORTING URS.
```

## Machine Specs

Operating System: Windows 10 Pro
Python Version: Python 3.9.6

## Additional Context

Got the same error on any redditor profile I tried to scrape.
Subreddit and URL scrapes export without any issues.

**Comment by JosephLai241** [comment]
Thank you for accurately filling out the bug template. 

This is an issue associated with [PRAW v7.3.0](https://praw.readthedocs.io/en/latest/package_info/change_log.html#id1). The `Redditor`'s `subreddit` attribute no longer returns a dictionary. A `UserSubreddit` object is returned instead, which is why the traceback reads `TypeError: Object of type UserSubreddit is not JSON serializable`.

My schedule has been very busy as of late, but I will find some time to address this bug during the weekend.
